# WAP to demonstrate try-except block

try:
    print(x)
except:
 print("An exception occurred")
